import datetime
import os

def save_to_document(response_text: str, directory: str = "./output"):
    """ Save the response text to a timestamped document in the specified directory."""
    os.makedirs(directory, exist_ok=True)

    # Create a markdown content with a title and timestamp

    markdown_content = f"""# AI Travel planner\n\n
    Generated on: {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}\n\n
    Created by: LLMOps\n\n
    ---
    {response_text}
    ---
    **This document was generated by an AI travel planner.Please verify the information before making any travel decisions.**
    """
    try:
        # write to a markdown file with utf-8 encoding
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = os.path.join(directory, f"travel_plan_{timestamp}.md")

        print(filename)

        with open(filename, "w", encoding='utf-8') as file:
            file.write(markdown_content)

        print(f"Response saved to {filename}")
        return filename
    except Exception as e:
        print(f"Error saving document: {e}")
        return None